/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAffiliateRouteImport } from './routes/app/affiliate'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppDonationsRouteImport } from './routes/app/donations'
import { Route as AppGameRouteImport } from './routes/app/game'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppPersonalInfoRouteImport } from './routes/app/personal-info'
import { Route as AppPlansRouteImport } from './routes/app/plans'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppSupportRouteImport } from './routes/app/support'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as AppTeamRouteImport } from './routes/app/team'
import { Route as AppWalletRouteImport } from './routes/app/wallet'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateRoute = AppAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDonationsRoute = AppDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AppRoute,
} as any)
const AppGameRoute = AppGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalInfoRoute = AppPersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/affiliate': typeof AppAffiliateRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/donations': typeof AppDonationsRoute
  '/app/game': typeof AppGameRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/personal-info': typeof AppPersonalInfoRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/affiliate': typeof AppAffiliateRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/donations': typeof AppDonationsRoute
  '/app/game': typeof AppGameRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/personal-info': typeof AppPersonalInfoRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/affiliate': typeof AppAffiliateRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/donations': typeof AppDonationsRoute
  '/app/game': typeof AppGameRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/personal-info': typeof AppPersonalInfoRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/app/affiliate'
    | '/app/dashboard'
    | '/app/donations'
    | '/app/game'
    | '/app/notifications'
    | '/app/personal-info'
    | '/app/plans'
    | '/app/profile'
    | '/app/support'
    | '/app/tasks'
    | '/app/team'
    | '/app/wallet'
    | '/auth/callback'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/app/affiliate'
    | '/app/dashboard'
    | '/app/donations'
    | '/app/game'
    | '/app/notifications'
    | '/app/personal-info'
    | '/app/plans'
    | '/app/profile'
    | '/app/support'
    | '/app/tasks'
    | '/app/team'
    | '/app/wallet'
    | '/auth/callback'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/app/affiliate'
    | '/app/dashboard'
    | '/app/donations'
    | '/app/game'
    | '/app/notifications'
    | '/app/personal-info'
    | '/app/plans'
    | '/app/profile'
    | '/app/support'
    | '/app/tasks'
    | '/app/team'
    | '/app/wallet'
    | '/auth/callback'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/affiliate': {
      id: '/app/affiliate'
      path: '/affiliate'
      fullPath: '/app/affiliate'
      preLoaderRoute: typeof AppAffiliateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donations': {
      id: '/app/donations'
      path: '/donations'
      fullPath: '/app/donations'
      preLoaderRoute: typeof AppDonationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/game': {
      id: '/app/game'
      path: '/game'
      fullPath: '/app/game'
      preLoaderRoute: typeof AppGameRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/personal-info': {
      id: '/app/personal-info'
      path: '/personal-info'
      fullPath: '/app/personal-info'
      preLoaderRoute: typeof AppPersonalInfoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AppRouteChildren {
  AppAffiliateRoute: typeof AppAffiliateRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDonationsRoute: typeof AppDonationsRoute
  AppGameRoute: typeof AppGameRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPersonalInfoRoute: typeof AppPersonalInfoRoute
  AppPlansRoute: typeof AppPlansRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAffiliateRoute: AppAffiliateRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDonationsRoute: AppDonationsRoute,
  AppGameRoute: AppGameRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPersonalInfoRoute: AppPersonalInfoRoute,
  AppPlansRoute: AppPlansRoute,
  AppProfileRoute: AppProfileRoute,
  AppSupportRoute: AppSupportRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
